export const WEATHER_HAS_ERRORED = "WEATHER_HAS_ERRORED";
export const WEATHER_IS_LOADING = "WEATHER_IS_LOADING";
export const WEATHER_GET_DATA_SUCCESS = "WEATHER_GET_DATA_SUCCESS";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";
